### ISSUE TITLE
tool does not open at all

### ISSUE THREAD

**Issue by IB2357** [Hetari/pyutube#10]
This SyntaxError message appears whatever the parameter I enter

```shell
➜  ~ pyutube --help

Traceback (most recent call last):
  File "/home/ibrahim/.pyenv/versions/3.11.9/bin/pyutube", line 5, in <module>
    from pyutube import cli
  File "/home/ibrahim/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pyutube/__init__.py", line 13, in <module>
    from .cli import app
  File "/home/ibrahim/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pyutube/cli.py", line 244
    console.print(f"All playlist are already downloaded in this directory, see '{
                  ^
SyntaxError: unterminated string literal (detected at line 244)

```

>[!note]
> When I downgrade to `pyutube==1.2.7` the interface works fine but videos cannot be downloaded

**Comment by IB2357** [comment]
now it works just fine.

thanks <3
