### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by pavlinbl4** [Hetari/pyutube#15]
Python 3.11
macOS 14.5 m1
`(venv) evgeniy@Evgeniys-Laptop Youtube_downloader % pytube ' https://youtu.be/xV02gHXZULM?si=c1hesUBmTom3EEEC'
Loading video...
Traceback (most recent call last):
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/bin/pytube", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
             ^^^^^^^^^^^^^^^
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evgeniy/PycharmProjects/Youtube_downloader/venv/lib/python3.11/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`

**Comment by pavlinbl4** [comment]
Thank you. At first time I was detected as a bot. I used https://github.com/JuanBindez/pytubefix/pull/209 and your app work fine.
